name: CI

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['*']

jobs:
  php-tests:
    name: Tests - PHP ${{ matrix.php }} ${{ matrix.dependency-version }}
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        php: ['8.2', '8.1', '8.0', '7.4']
        dependency-version: ['']

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: none
          ini-values: expose_php=1
      - name: Install dependencies
        run: 'composer update ${{ matrix.dependency-version }} --no-interaction --prefer-dist --no-progress'
      - name: Execute Unit Tests
        run: 'vendor/bin/phpunit'
